export default [
  {
    id: '1',
    name: '首页',
    type: 1,
    icon: 'home',
    level: 1,
    show: true,
    routeName: 'default',
  },
  {
    id: '2',
    name: '权限管理',
    type: 0,
    icon: 'key',
    level: 1,
    show: true,
    children: [
      {
        id: '2-1',
        name: '账户管理',
        type: 1,
        icon: 'user',
        level: 2,
        show: true,
        routeName: 'admin_account',
      },
    ],
  },
  {
    id: '3',
    name: '布局组件',
    type: 0,
    icon: 'layout',
    level: 1,
    show: true,
    children: [
      {
        id: '3-1',
        name: '容器(Container)',
        type: 1,
        icon: 'container',
        level: 2,
        show: true,
        routeName: 'doc_layout_container',
      },
      {
        id: '3-2',
        name: '盒子(Box)',
        type: 1,
        icon: 'box',
        level: 2,
        show: true,
        routeName: 'doc_layout_box',
      },
      {
        id: '3-3',
        name: '弹性布局(Flex)',
        type: 1,
        icon: 'list',
        level: 2,
        show: true,
        routeName: 'doc_layout_flex',
      },
      {
        id: '3-4',
        name: '滚动条(Scrollbar)',
        type: 1,
        icon: 'list',
        level: 2,
        show: true,
        routeName: 'doc_layout_scrollbar',
      },
    ],
  },
  {
    id: '4',
    name: '基础组件',
    type: 0,
    icon: 'component',
    level: 1,
    show: true,
    children: [
      {
        id: '4-1',
        name: '图标(Icon)',
        type: 1,
        icon: 'icon',
        level: 2,
        show: true,
        routeName: 'doc_base_icon',
      },
      {
        id: '4-2',
        name: '按钮(Button)',
        type: 1,
        icon: 'button',
        level: 2,
        show: true,
        routeName: 'doc_base_button',
      },
    ],
  },
  {
    id: '5',
    name: '高级组件',
    type: 0,
    icon: 'component',
    level: 1,
    show: true,
    children: [
      {
        id: '5-1',
        name: '对话框(Dialog)',
        type: 1,
        icon: 'chat-o',
        level: 2,
        show: true,
        routeName: 'doc_advanced_dialog',
      },
    ],
  },
]
