export default [
  {
    id: '1',
    name: '首页',
    type: 1,
    icon: 'home',
    level: 1,
    show: true,
    routeName: 'default',
  },
  {
    id: '2',
    name: '权限管理',
    type: 0,
    icon: 'key',
    level: 1,
    show: true,
    children: [
      {
        id: '2-1',
        name: '账户管理',
        type: 1,
        icon: 'user',
        level: 2,
        show: true,
        routeName: 'admin_account',
      },
    ],
  },
  {
    id: '3',
    name: '基础组件',
    type: 0,
    icon: 'component',
    level: 1,
    show: true,
    routeName: '',
    children: [
      {
        id: '3-1',
        name: '图标',
        type: 1,
        icon: 'icon',
        level: 2,
        show: true,
        routeName: 'doc_icon',
      },
      {
        id: '3-2',
        name: '按钮',
        type: 1,
        icon: 'button',
        level: 2,
        show: true,
        routeName: 'doc_button',
      },
    ],
  },
  {
    id: '4',
    name: '布局组件',
    type: 0,
    icon: 'layout',
    level: 1,
    show: true,
    routeName: '',
    children: [
      {
        id: '4-1',
        name: '容器(Container)',
        type: 1,
        icon: 'container',
        level: 2,
        show: true,
        routeName: 'doc_container',
      },
      {
        id: '4-2',
        name: '盒子(Box)',
        type: 1,
        icon: 'box',
        level: 2,
        show: true,
        routeName: 'doc_box',
      },
    ],
  },
]
